name: Update versions

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Fetch latest versions
        uses: nick-fields/retry@v4
        with:
          max_attempts: 5
          timeout_minutes: 10
          command: |
            set -uo pipefail
            TRAEFIK=$(git ls-remote --tags https://github.com/traefik/traefik.git/  \
              | awk -F/ '/v[0-9\.]+$/ {gsub("v", ""); print $3}' \
              | sort -V | tail -1)

            : ${TRAEFIK:?}
  
            jq \
              --arg traefik "$TRAEFIK" \
              '
                .traefik.version = $traefik
              ' sources.json > tmp.json && mv tmp.json sources.json

            git diff sources.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update-versions
          delete-branch: true
          title: Update Traefik
          commit-message: Update Traefik
