name: Update versions

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Fetch latest versions
        uses: nick-fields/retry@v4
        with:
          max_attempts: 5
          timeout_minutes: 10
          command: |
            set -uo pipefail
            TRAEFIK=$(git ls-remote --tags https://github.com/traefik/traefik.git/  \
              | awk -F/ '{print $3}' \
              | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
              | sed 's/^v//' \
              | sort -V \
              | tail -1)
  
            yq -i ".traefik= \"$TRAEFIK\"" versions.yaml
            git diff versions.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update-versions
          delete-branch: true
          title: Update Traefik
          commit-message: Update Traefik
